# Use an official Node.js image as the base
FROM node:21-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Command to run the app in development mode with --host option
CMD ["npm", "run", "dev", "--", "--host"]
